### ISSUE TITLE
STK PUSH CONFIRMATION REQUEST

### ISSUE THREAD

**Issue by imodoiepale** [Fortune-dot/Tiny-Js#1]
<H1>Can we improve the resultant name to the Original TILL NUMBER NAME</H1>
<H2> THAT IS FROM TINY PESA TO--- [ PREFERED TILL NAME ] using settings in the User Dashboard</H2>

<BR><BR>
![2432c77e-4191-4f5b-9004-5a4bbcb8fd6b](https://user-images.githubusercontent.com/101794204/184261999-995f6d25-47a6-4868-aa0b-2f71d1071c97.jpg)
.

**Comment by Fortune-dot** [comment]
This is a thing that may be implemented in future but the team currently uses this as it is
